# use temp_dir crate
disallowed-methods = ["std::env::temp_dir"]

allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true
absolute-paths-max-segments = 2
semicolon-inside-block-ignore-singleline = true
