newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true

### Nightly Options ###

# Imports
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"

# Structs & Enums
enum_discrim_align_threshold = 10
struct_field_align_threshold = 10
reorder_impl_items = true

# Comments & Attrs
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Misc
format_strings = true
overflow_delimited_expr = true
