[unstable]
codegen-backend = true

[profile.cl]
codegen-backend = "cranelift"
opt-level = 1

[profile.cl.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
